
- type: replace
  path: /instance_groups/name=adapter/instances
  value: 2
- type: replace
  path: /instance_groups/name=eirini/instances
  value: 2
- type: replace
  path: /instance_groups/name=nats/instances
  value: 2
- type: replace
  path: /instance_groups/name=uaa/instances
  value: 2
- type: replace
  path: /instance_groups/name=bits/instances
  value: 2
- type: replace
  path: /instance_groups/name=api/instances
  value: 1  # second instance of api does not get ready because of route_registrar
- type: replace
  path: /instance_groups/name=cc-worker/instances
  value: 2
- type: replace
  path: /instance_groups/name=scheduler/instances
  value: 2
- type: replace
  path: /instance_groups/name=router/instances
  value: 2
- type: replace
  path: /instance_groups/name=doppler/instances
  value: 2
- type: replace
  path: /instance_groups/name=log-api/instances
  value: 2
- type: replace
  path: /instance_groups/name=database/instances
  value: 2
