---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-single-availability
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
{{ if not .Values.sizing.HA -}}
  ops: |
    - type: replace
      path: /instance_groups/name=nats/instances
      value: 1
    - type: replace
      path: /instance_groups/name=adapter/instances
      value: 1
    - type: replace
      path: /instance_groups/name=database/instances
      value: 1
    - type: replace
      path: /instance_groups/name=diego-api/instances
      value: 1
    - type: replace
      path: /instance_groups/name=uaa/instances
      value: 1
    {{- if eq .Values.features.blobstore.provider "singleton" }}
    - type: replace
      path: /instance_groups/name=singleton-blobstore/instances
      value: 1
    {{- end }}
    - type: replace
      path: /instance_groups/name=api/instances
      value: 1
    - type: replace
      path: /instance_groups/name=cc-worker/instances
      value: 1
    - type: replace
      path: /instance_groups/name=scheduler/instances
      value: 1
    - type: replace
      path: /instance_groups/name=router/instances
      value: 1
    - type: replace
      path: /instance_groups/name=doppler/instances
      value: 1
    - type: replace
      path: /instance_groups/name=diego-cell/instances
      value: 1
    - type: replace
      path: /instance_groups/name=log-api/instances
      value: 1
    - type: remove
      path: /instance_groups/name=nats/azs?
    - type: remove
      path: /instance_groups/name=adapter/azs?
    - type: remove
      path: /instance_groups/name=database/azs?
    - type: remove
      path: /instance_groups/name=diego-api/azs?
    - type: remove
      path: /instance_groups/name=uaa/azs?
    {{- if eq .Values.features.blobstore.provider "singleton" }}
    - type: remove
      path: /instance_groups/name=singleton-blobstore/azs?
    {{- end }}
    - type: remove
      path: /instance_groups/name=api/azs?
    - type: remove
      path: /instance_groups/name=cc-worker/azs?
    - type: remove
      path: /instance_groups/name=scheduler/azs?
    - type: remove
      path: /instance_groups/name=router/azs?
    - type: remove
      path: /instance_groups/name=doppler/azs?
    - type: remove
      path: /instance_groups/name=diego-cell/azs?
    - type: remove
      path: /instance_groups/name=log-api/azs?

    {{- if .Values.features.eirini.enabled }}
    - type: replace
      path: /instance_groups/name=bits/instances
      value: 1
    - type: remove
      path: /instance_groups/name=bits/azs?

    - type: replace
      path: /instance_groups/name=eirini/instances
      value: 1
    - type: remove
      path: /instance_groups/name=eirini/azs?
    {{- end }}

{{- else }}
  ops: |
    - type: replace
      path: /instance_groups/name=nats/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=adapter/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    
    - type: remove
      path: /instance_groups/name=database/azs?
    - type: replace
      path: /instance_groups/name=database/instances
      value: 1
    
    - type: replace
      path: /instance_groups/name=diego-api/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=uaa/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    {{- if eq .Values.features.blobstore.provider "singleton" }}
    - type: remove
      path: /instance_groups/name=singleton-blobstore/azs?
    - type: replace
      path: /instance_groups/name=singleton-blobstore/instances
      value: 1
    {{- end }}
    - type: replace
      path: /instance_groups/name=api/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=cc-worker/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=scheduler/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=router/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=doppler/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=diego-cell/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    - type: replace
      path: /instance_groups/name=log-api/azs?
      value: ["europe-west1-b", "europe-west1-c"]

    {{- if .Values.features.eirini.enabled }}
    - type: replace
      path: /instance_groups/name=bits/instances
      value: 1
    - type: remove
      path: /instance_groups/name=bits/azs?

    - type: replace
      path: /instance_groups/name=eirini/azs?
      value: ["europe-west1-b", "europe-west1-c"]
    {{- end }}
{{- end }}